language: python
python:
  - '3.5'
cache: pip

addons:
  chrome: stable

services:
  - memcached

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y unzip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

before_script: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip .
  - rm chromedriver_linux64.zip
  - export PATH=$PATH:$PWD/chromedriver
#  - sudo mv -f ~/chromedriver /usr/local/share/
#  - sudo chmod +x /usr/local/share/chromedriver
#  - export PATH=$PATH:/usr/local/share/chrome-driver

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - python manage.py test

deploy:
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: CDAforBBM
    deployment_group: BBMgroup
    region: ap-northeast-2