language: python
python:
  - '3.5'

script:
 - sudo apt-get update

addons:
  chrome: stable

install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - export PATH=$PATH:/usr/local/share/chrome-driver


services:
  - memcached

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - python manage.py test

deploy:
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: CDAforBBM
    deployment_group: BBMgroup
    region: ap-northeast-2