language: python
python:
  - '3.5'

services:
  - memcached

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - python manage.py test

deploy:
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: CDAforBBM
    deployment_group: BBMgroup
    region: ap-northeast-2